server:
  port: 8081

employee:
  api:
    url: http://localhost:8080/employees/{firstName}

spring:
  boot:
    admin:
      client:
        instance:
          service-url: http://localhost:${server.port}
        url: http://localhost:8083
  application:
    name: staff-location-api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true 