server:
  port: 8081

employee:
  api:
    url: http://localhost:8080/employees/{firstName}

spring:
  boot:
    admin:
      client:
        instance:
          service-url: http://localhost:${server.port}
        url: http://localhost:8083
      notify:
        teams:
          enabled: true
          webhook-url: "https://outlook.office.com/webhook/your-teams-webhook-url-here"
          message: "**#{instance.registration.name}** (#{instance.id}) is *#{lastStatus}*"

  application:
    name: staff-location-api

management:
  endpoints:
    # access:
    #   default: none
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

    